### ISSUE TITLE
Doesn't compile on Qt 5.10.1

### ISSUE THREAD

**Issue by shujaatak** [qmlc/qmlc#37]
Is this compatible with Qt5.10.1?
It throws a lot of errors like:
`
C:\Qt_Workspace\qmlc-master\qmlc-master\qmccompiler\qmlc.cpp:30: error: private/qqmlcompiler_p.h: No such file or directory`
